services:
  ftp-server:
    container_name: ftp_container
    environment:
      - USERS=${FTP_INFO}
      - ADDRESS=${SERVER_ADDR}
    image: delfer/alpine-ftp-server
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - "./data:/home/user/${FTP_USER}"
    restart: always
  nginx:
    image: nginx:alpine
    container_name: ftp_webserver
    restart: unless-stopped
    ports:
      - "${WEBSERVER_PORT}:80"
    volumes:
      - "./data:/var/www"
      - "./nginx:/etc/nginx/conf.d/"
